# Generated by Django 5.0.7 on 2024-07-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_remove_movie_actors"),
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="movies",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="board.movie",
            ),
        ),
    ]
