# Generated by Django 5.0.4 on 2024-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0002_remove_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("character", models.CharField(max_length=255)),
            ],
        ),
    ]
