# Generated by Django 5.0.7 on 2024-07-15 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0003_actor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="location",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="university",
        ),
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("location", models.CharField(default="", max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
