# Generated by Django 5.0.7 on 2024-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=255)),
                ('title_eng', models.CharField(max_length=255)),
                ('poster_url', models.URLField()),
                ('genre', models.CharField(max_length=255)),
                ('showtime', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('plot', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=255)),
                ('director_image_url', models.URLField()),
            ],
        ),
    ]
