# Generated by Django 5.0.7 on 2024-07-15 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_movie_actors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
    ]
